spring:
  application:
    name: weather-service
  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
configuration:
  open-weather:
    appid: 02f6d80d4eb4063b7e1e98ac6b6c5f31
    url: http://api.openweathermap.org/data/2.5/weather?q={city}&APPID=${configuration.open-weather.appid}
    #    url: http://api.openweathermap.org/data/2.5/weather?q=London&APPID=02f6d80d4eb4063b7e1e98ac6b6c5f31

