CREATE TABLE public.sys (
    sys_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type INT,
    id INT,
    message DOUBLE,
    country VARCHAR(255),
    sunrise INT,
    sunset INT,
    weather_response_id INT
);
