CREATE TABLE public.main (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temp NUMBER,
    pressure NUMBER,
    humidity NUMBER,
    temp_min NUMBER,
    temp_max NUMBER,
    weather_response_id NUMBER
);
