CREATE TABLE public.weather_response (
    weather_response_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coord NUMBER,
    weather NUMBER,
    main NUMBER,
    wind NUMBER,
    clouds NUMBER,
    sys NUMBER,
    base VARCHAR(255),
    dt NUMBER,
    visibility NUMBER,
    id NUMBER,
    name VARCHAR(255),
    cod NUMBER
);
