CREATE TABLE public.weather_response (
    weather_response_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coord INT,
    weather INT,
    main INT,
    wind INT,
    clouds INT,
    sys INT,
    base VARCHAR(255),
    dt INT,
    visibility INT,
    id INT,
    name VARCHAR(255),
    cod INT
);
