CREATE TABLE public.sys (
    sys_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type NUMBER,
    id NUMBER,
    message NUMBER,
    country VARCHAR(255),
    sunrise NUMBER,
    sunset NUMBER,
    weather_response_id NUMBER
);
