CREATE TABLE public.main (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temp DOUBLE,
    pressure INT,
    humidity INT,
    temp_min DOUBLE,
    temp_max DOUBLE,
    weather_response_id INT
);
